# Generated by Django 3.2.2 on 2021-05-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ZIPFILE', models.FileField(upload_to='zipfiles/')),
            ],
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
